version: '3.8'
services:
  app:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    env_file: .env
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
      - ./migrations:/usr/src/app/migrations
      - ./config:/usr/src/app/config
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./tokens:/usr/src/app/tokens
      - ./uploads:/usr/src/app/uploads
    depends_on:
      - db
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-botuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-botpass}
      POSTGRES_DB: ${POSTGRES_DB:-botdb}
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
